[[mounts]]
  source = "node_modules/@hyas/core/assets"
  target = "assets"

[[mounts]]
  source = "node_modules/@hyas/core/layouts"
  target = "layouts"

[[mounts]]
  source = "node_modules/hyas/assets"
  target = "assets"

[[mounts]]
  source = "node_modules/@hyas/seo/layouts"
  target = "layouts"

[[mounts]]
  source = "node_modules/@hyas/images/layouts"
  target = "layouts"

[[mounts]]
  source = "themes/bolt-blog/archetypes"
  target = "archetypes"

[[mounts]]
  source = "themes/bolt-blog/assets"
  target = "assets"

[[mounts]]
  source = "themes/bolt-blog/content"
  target = "content"

[[mounts]]
  source = "themes/bolt-blog/layouts"
  target = "layouts"

[[mounts]]
  source = "themes/bolt-blog/static"
  target = "static"

[[mounts]]
  source = "archetypes"
  target = "archetypes"

[[mounts]]
  source = "assets"
  target = "assets"

[[mounts]]
  source = "content"
  target = "content"

[[mounts]]
  source = "layouts"
  target = "layouts"

[[mounts]]
  source = "static"
  target = "static"
